import { CommonModule } from '@angular/common';
import { Component, EventEmitter, Output } from '@angular/core';
import {
    FormControl,
    FormGroup,
    ReactiveFormsModule,
    Validators,
} from '@angular/forms';
import { creditur } from '../../../model/creditur';

@Component({
    selector: 'app-form',
    standalone: true,
    imports: [CommonModule, ReactiveFormsModule],
    templateUrl: './form.html',
    styleUrl: './form.scss',
})
export class FormComponent {
    @Output() addCreditur = new EventEmitter<creditur>();

    crediturForm = new FormGroup({
        name: new FormControl('', [Validators.required, Validators.minLength(3)]),
        age: new FormControl('', [Validators.required, Validators.min(1), Validators.max(120)]),
        job: new FormControl('', [Validators.required, Validators.minLength(3)]),
    });

    onSubmit(): void {
        if (!this.crediturForm.valid) return;

        const formValue = this.crediturForm.value;
        const newCreditur: creditur = {
            id: 0, // Will be auto-generated by service
            name: formValue.name || '',
            age: Number(formValue.age) || 0,
            job: formValue.job || '',
            creditScore: 0 // Will be auto-generated by service
        };

        this.addCreditur.emit(newCreditur);
        this.crediturForm.reset();
    }

    // Helper method untuk template
    isFieldInvalid(fieldName: string): boolean {
        const field = this.crediturForm.get(fieldName);
        return !!(field?.invalid && field?.touched);
    }
}
